# Generated by Django 3.0.7 on 2021-02-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('SCA', 'Secretaria da Cultura'), ('SDS', 'Secretaria de Desenvolvimento Social')], max_length=3)),
                ('url', models.CharField(max_length=2083)),
                ('title', models.TextField()),
                ('subtitle', models.TextField()),
                ('published', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('collected', models.DateTimeField(auto_now_add=True)),
                ('main_text', models.TextField()),
                ('tags', models.ManyToManyField(to='dsb_rest.Tag')),
            ],
        ),
    ]
