# Generated by Django 3.0.7 on 2021-02-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsb_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='subtitle',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
